# Generated by Django 2.2.1 on 2019-06-21 10:03

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190615_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
